#!/bin/bash

# Make sure SPARK_HOME is set
if [ "a" == "a""$SPARK_HOME" ]; then
  echo SPARK_HOME not set.  Please set SPARK_HOME environment variable and try again.
  exit 1
fi

# Make sure SCALA_HOME is set
if [ "a" == "a""$SCALA_HOME" ]; then
  echo SCALA_HOME not set.  Please set SCALA_HOME environment variable and try again.
  exit 1
fi


function addJarToSpark {
  groupId=$1
  artifactId=$2
  version=$3
  qualifier=$4
  echo Group: ${groupId}
  echo artifact: ${artifactId}
  echo version: ${version}
  echo qualifer: ${qualifier}

  groupDir=`echo ${groupId} | sed 's|\.|/|g'`
  repo=${HOME}/.m2/repository
  jardir=${repo}/${groupDir}/${artifactId}/${version}
  if [ X${qualifier} = X ]
  then
	  echo No qualifer
	  jar=${jardir}/${artifactId}-${version}.jar
  else
	  echo qualifer
	  jar=${jardir}/${artifactId}-${version}-${qualifier}.jar
  fi


  # Testing for existence of jar
  if [ ! -e ${jar} ]
  then
      echo Error: Looking for ${jar} - not found
      exit
  fi

  # Add the jar to the classpath
  if [ "a" == "a"${ADD_JARS} ]; then
    export ADD_JARS=${jar}
  else
    export ADD_JARS=${ADD_JARS},${jar}
  fi
}






# Set up the spark classpath
# our own jars
addJarToSpark com.oculusinfo math-utilities 0.3-SNAPSHOT
addJarToSpark com.oculusinfo binning-utilities 0.3-SNAPSHOT
addJarToSpark com.oculusinfo tile-generation 0.3-SNAPSHOT
addJarToSpark com.oculusinfo tile-service 0.3-SNAPSHOT classes

# framework-related jars
addJarToSpark org.apache.hbase hbase 0.94.15-cdh4.6.0
addJarToSpark org.scala-lang scala-library 2.10.3
addJarToSpark org.json json 20090211


# export MASTER=local[8]
# export SPARK_MEM=4g

echo Running Spark from $SPARK_HOME
echo Running Spark on $MASTER
echo Running Spark with $SPARK_MEM
echo Running Spark with jars=$ADD_JARS

$SPARK_HOME/bin/spark-shell $*
