#!/bin/bash

# Make sure SPARK_HOME is set
if [ "a" == "a""$SPARK_HOME" ]; then
  echo SPARK_HOME not set.  Please set SPARK_HOME environment variable and try again.
  exit 1
fi

# Make sure SCALA_HOME is set
if [ "a" == "a""$SCALA_HOME" ]; then
  echo SCALA_HOME not set.  Please set SCALA_HOME environment variable and try again.
  exit 1
fi

# export SPARK_CLASSPATH=$SCALA_HOME/libexec/lib/'*'

function addToSparkClasspath {
  scriptGroupId=$1
  scriptArtifactId=$2
  scriptVersion=$3
  groupDir=`echo ${scriptGroupId} | sed 's|\.|/|g'`
  repo=${HOME}/.m2/repository
  jardir=${repo}/${groupDir}/${scriptArtifactId}/${scriptVersion}
  jar=${jardir}/${scriptArtifactId}-${scriptVersion}.jar

  # Testing for existence of jar
  if [ ! -e ${jar} ]
  then
      echo Error: Looking for ${jar} - not found
      exit
  fi

  # Add the jar to the classpath
  if [ "a" == "a"${SPARK_CLASSPATH} ]; then
    export SPARK_CLASSPATH=${jar}
  else
    export SPARK_CLASSPATH=${SPARK_CLASSPATH}:${jar}
  fi
}






# Set up the spark classpath

# Twitter-specific jars
addToSparkClasspath com.oculusinfo twitter-utilities @project.version@

# other oculus binning jars
addToSparkClasspath com.oculusinfo math-utilities @project.version@
addToSparkClasspath com.oculusinfo binning-utilities @project.version@
addToSparkClasspath com.oculusinfo tile-generation @project.version@
addToSparkClasspath com.oculusinfo twitter-demo-day-utilities @project.version@

# framework-related jars
addToSparkClasspath org.apache.hbase hbase ${hbase-version}

# additional stuff needed to use avro serialization

# and just to make sure, scala itself
addToSparkClasspath org.scala-lang scala-library ${scala-version}




# export MASTER=local[8]
# export SPARK_MEM=4g

echo Running Spark from $SPARK_HOME
echo Running Spark on $MASTER
echo Running Spark with $SPARK_MEM
echo Running Spark with classpath=$SPARK_CLASSPATH

$SPARK_HOME/bin/spark-class $*
